<?php
use rosasurfer\core\di\facade\Form;
use rosasurfer\rt\model\Test;

/** @var Test $test */
$test = Form::get('test');
$trades = $test->getTrades();
?>
<script src="<?=asset('/js/chartjs/Chart-2.6.0.js')?>"></script>

<canvas id="canvas" width="700" height="500" style="margin:auto"></canvas>

<script>
Chart.defaults.global.responsive = false;
Chart.defaults.global.animation  = false;

var Color = {
    black:  'rgb(  0,   0,   0)',
    white:  'rgb(255, 255, 255)',
    red:    'rgb(255,  99, 132)',
    orange: 'rgb(255, 159,  64)',
    yellow: 'rgb(255, 205,  86)',
    green:  'rgb( 75, 192, 192)',
    blue:   'rgb( 54, 162, 235)',
    purple: 'rgb(153, 102, 255)',
    grey:   'rgb(201, 203, 207)'
};

var chart = new Chart('canvas', {
    type: 'line',
    data: {
        datasets: [{
            label: 'Equity',
            backgroundColor: Color.red,
            borderColor:     Color.red,
            fill:            false,
            borderWidth:     1,
            lineTension:     0,
            pointRadius:     0,
            data: [
                <?php
                foreach ($trades as $i => $trade) {
                    $time   = gmdate(DATE_ISO8601, strtotime($trade->getCloseTime().' GMT'));   // '2014-09-08T08:02:17-05:00' (ISO 8601)
                    $profit = $trade->getProfit();
                    if ($i++) echo ','.NL;
                    echo '{x: "'.$time.'", y: '.$profit.'}';
                    if ($i > 100) {
                        break;
                    }
                }
                ?>
            ],
        }]
    },
    options: {
        scales: {
            xAxes: [{
                type: 'time',
            }],
        }
    }
});
</script>
