<?
$baseUri = strLeft($request->getApplicationBaseUri(), -1);
?>
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">

   <title>Home</title>
   <script type="text/javascript" src="<?=$baseUri.vUrl('/js/rosasurfer.js')?>"></script>
</head>

<body>
&nbsp;&nbsp;&nbsp;<a href="<?=$baseUri?>/" style="color:blue">Home</a>
&nbsp;&nbsp;&nbsp;<a href="<?=$baseUri?>/uploadAccountHistory.php" style="color:blue">UploadAccountHistory</a>
<br>
<br>

</body>
</html>
