
<nav class="navbar navbar-default navbar-custom">
   <div class="container-fluid">
      <div class="navbar-header">
         <a class="navbar-brand" href="<?=route('home')?>">RSX</a>
      </div>

      <div class="nav-collapse">
         <ul class="nav navbar-nav navbar-left">
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tests <span class="caret"></span></a>
               <ul class="dropdown-menu">
                  <li><a href="<?=route('tests.sorted')?>">Sortable</a></li>
               </ul>
            </li>

            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Chart.js <span class="caret"></span></a>
               <ul class="dropdown-menu">
                  <li><a href="<?=route('chartjs.bar')?>"          >Bars</a></li>
                  <li><a href="<?=route('chartjs.scatter')?>?id=62">Distribution</a></li>
                  <li><a href="<?=route('chartjs.line')?>?id=32"   >Equity</a></li>
               </ul>
            </li>

            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">HighCharts <span class="caret"></span></a>
               <ul class="dropdown-menu">
                  <li><a href="<?=route('highcharts.line')?>?id=32" >Equity</a></li>
               </ul>
            </li>

            <li><a href="<?=route('history')?>">History</a></li>
            <li><a href="<?=route('symbols')?>">Symbols</a></li>
         </ul>

         <ul class="nav navbar-nav navbar-right">
            <li><a href="<?=route('login')?>">Login</a></li>
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Help <span class="caret"></span></a>
               <ul class="dropdown-menu">
                  <li><a href="<?=route('contact')?>">Contact</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="<?=route('about')?>">About</a></li>
               </ul>
            </li>
         </ul>
      </div>
   </div>
</nav>
