<?php
use rosasurfer\xtrade\XTrade;
use rosasurfer\xtrade\model\metatrader\Test;
use function rosasurfer\xtrade\prettyRecoveryTime;
use function rosasurfer\xtrade\prettyTimeRange;

$tests = Test::dao()->findAll('select * from :Test order by strategy, created');
?>

<?foreach ($request->getActionErrors() as $value) {?><div class="alert alert-danger textcenter"><p><?=hsc($value)?></p></div><?}?>


<div class="panel panel-default">
   <div class="panel-heading">Found <?=$size=sizeOf($tests)?> test<?=pluralize($size)?>.</div>

   <table class="table table-striped table-hover table-bordered">
   <thead>
   <tr>
      <th style="vertical-align:middle; text-align:center">#</th>
      <th style="vertical-align:middle; text-align:left" title="tested strategy">Strategy</th>
      <th style="vertical-align:middle; text-align:center" title="test report id">Test</th>
      <th style="vertical-align:middle; text-align:center" title="tested symbol and timeframe">Symbol</th>
      <th style="vertical-align:middle; text-align:center" title="tested time range">Time</th>
      <th style="vertical-align:middle; text-align:center" title="number of trades">Trades</th>
      <th style="vertical-align:middle; text-align:center" title="average amount of pips per trade for a non-compounding strategy with fixed lotsize">Pips/Trade</th>
      <th style="vertical-align:middle; text-align:center" title="simplified non-normalized Sharpe ratio">Sharpe</th>
      <th style="vertical-align:middle; text-align:center" title="simplified non-normalized Sortino ratio">Sortino</th>
      <th style="vertical-align:middle; text-align:center" title="simplified monthly Calmar ratio">Calmar</th>
      <th style="vertical-align:middle; text-align:center" title="maximum drawdown recovery time in days">max. Recovery Time</th>
   </tr>
   </thead>

   <tbody>
   <?
   /** @var Test $test */
   foreach ($tests as $i => $test) {
      $strategy        = $test->getStrategy();
      $report          = $test->getReportingSymbol();
      $symbol          = $test->getSymbol();
      $period          = XTrade::periodDescription($test->getTimeframe());
      $timeRange       = prettyTimeRange($test->getStartTime(), $test->getEndTime());
      $numTrades       = $test->getStats()->getTrades();
      $avgPips         = $test->getStats()->getAvgPips();
      $sharpe          = $test->getStats()->getSharpeRatio();
      $sortino         = $test->getStats()->getSortinoRatio();
      $calmar          = $test->getStats()->getCalmarRatio();
      $maxRecoveryTime = prettyRecoveryTime($test->getStats()->getMaxRecoveryTime());
   ?>
   <tr style="text-align:center">
      <th style="vertical-align:middle; text-align:center" scope="row"><?=($i+1)?></th>
      <td style="vertical-align:middle; text-align:left"><?=hsc($strategy)?></td>
      <td style="vertical-align:middle" nowrap>
         <a href="<?=route('test.detail').'?id='.$test->getId()?>"><?=hsc($report)?></a>
      </td>
      <td style="vertical-align:middle"><?=$symbol.', '.$period?></td>
      <td style="vertical-align:middle"><?=$timeRange?></td>
      <td style="vertical-align:middle"><?=numf($numTrades, 0)?></td>
      <td style="vertical-align:middle"><?=sprintf('%+.1f', $avgPips)?></td>
      <td style="vertical-align:middle"><?=rtrim(sprintf('%.4f', $sharpe), '.0')?></td>
      <td style="vertical-align:middle"><?=rtrim(sprintf('%.4f', $sortino), '.0')?></td>
      <td style="vertical-align:middle"><?=rtrim(sprintf('%.4f', $calmar), '.0')?></td>
      <td style="vertical-align:middle"><?=$maxRecoveryTime?></td>
   </tr>
   <?}?>
   </tbody>
   </table>
</div>
