<?php
namespace rosasurfer\xtrade\view;
use rosasurfer\xtrade\XTrade;
use rosasurfer\xtrade\model\metatrader\Test;
use function rosasurfer\xtrade\prettyTimeRange;

$tests = Test::dao()->findAll('select * from :Test order by strategy, created');

foreach ($request->getActionErrors() as $value) {?>
   <div class="alert alert-danger textcenter">
      <p><?=$value?></p>
   </div>
<?}?>

<div class="panel panel-default">
   <div class="panel-heading">Found <?=$size=sizeOf($tests)?> test<?=pluralize($size)?>.</div>

   <table class="table table-striped table-hover table-bordered">
   <thead>
   <tr>
      <th style="vertical-align:middle; text-align:center">#</th>
      <th style="vertical-align:middle; text-align:left">Strategy</th>
      <th style="vertical-align:middle; text-align:center">Test</th>
      <th style="vertical-align:middle; text-align:center">Symbol</th>
      <th style="vertical-align:middle; text-align:center">Time Range</th>
      <th style="vertical-align:middle; text-align:center">Trades</th>
      <th style="vertical-align:middle; text-align:center">Avg Pips/Lot</th>
   </tr>
   </thead>

   <tbody>
   <?
   /** @var Test $test */
   foreach ($tests as $i => $test) {
      $strategy  = $test->getStrategy();
      $report    = $test->getReportingSymbol();
      $symbol    = $test->getSymbol();
      $period    = Xtrade::periodDescription($test->getTimeframe());
      $timeRange = prettyTimeRange($test->getStartTime(), $test->getEndTime());
      $numTrades = $test->getStats()->getTrades();
      $avgPips   = $test->getStats()->getAvgPips();
   ?>
   <tr style="text-align:center">
      <th style="vertical-align:middle; text-align:center" scope="row"><?=($i+1)?></th>
      <td style="vertical-align:middle; text-align:left"><?=$strategy?></td>
      <td style="vertical-align:middle" nowrap>
         <a href="<?=route('test.detail').'?id='.$test->getId()?>"><?=$report?></a>
      </td>
      <td style="vertical-align:middle"><?=$symbol.', '.$period?></td>
      <td style="vertical-align:middle"><?=$timeRange?></td>
      <td style="vertical-align:middle"><?=numf($numTrades, 0)?></td>
      <td style="vertical-align:middle"><?=sprintf('%+.1f', $avgPips)?></td>
   </tr>
   <?}?>
   </tbody>
   </table>
</div>
