<?php
use rosasurfer\ministruts\Request;
use rosasurfer\xtrade\XTrade;
use rosasurfer\xtrade\model\metatrader\Test;

use function rosasurfer\xtrade\prettyTimeRange;

/** @var Request $request */
/** @var Test[]  $tests   */
$tests = Test::dao()->findAll('select * from :Test order by strategy, created, reportingsymbol');
?>

<link href="<?=asset('/css/tablesorter/theme.blue.min.css')?>" id="tablesorter-theme" rel="stylesheet">
<script src="<?=asset('/js/tablesorter/jquery.tablesorter.combined.js')?>"></script>

<?foreach ($request->getActionMessages() as $message) {?>
    <div class="alert alert-danger textcenter"><p><?=hsc($message)?></p></div>
<?}?>


Found <?=$size=sizeOf($tests)?> test<?=pluralize($size)?>

<table id="testTable" class="tablesorter">
<thead>
<tr>
    <th style="vertical-align:middle; text-align:left" title="tested strategy">Strategy</th>
    <th style="vertical-align:middle; text-align:center" title="test report id">Test</th>
    <th style="vertical-align:middle; text-align:center" title="tested symbol and timeframe">Symbol</th>
    <th style="vertical-align:middle; text-align:center" title="tested time period">Test Period</th>
    <th style="vertical-align:middle; text-align:center" title="number of trades">Trades</th>
    <th style="vertical-align:middle; text-align:center" title="average amount of pips per trade">Pips/Trade</th>
    <th style="vertical-align:middle; text-align:center" title="simplified non-normalized Sharpe ratio">Sharpe</th>
    <th style="vertical-align:middle; text-align:center" title="simplified non-normalized Sortino ratio">Sortino</th>
    <th style="vertical-align:middle; text-align:center" title="simplified monthly Calmar ratio">Calmar</th>
    <th style="vertical-align:middle; text-align:center" title="maximum drawdown recovery time">Recovery Time</th>
</tr>
</thead>

<tbody>
<?
foreach ($tests as $test) {
    $strategy        = $test->getStrategy();
    $report          = $test->getReportingSymbol();
    $symbol          = $test->getSymbol();
    $period          = XTrade::periodDescription($test->getTimeframe());
    $timeRange       = prettyTimeRange($test->getStartTime(), $test->getEndTime());
    $numTrades       = $test->getStats()->getTrades();
    $avgPips         = $test->getStats()->getAvgPips();
    $sharpe          = $test->getStats()->getSharpeRatio();
    $sortino         = $test->getStats()->getSortinoRatio();
    $calmar          = $test->getStats()->getCalmarRatio();
    $maxRecoveryTime = $test->getStats()->getMaxRecoveryTime()/DAYS;
?>
<tr style="text-align:center">
    <td style="vertical-align:middle; text-align:left"><?=hsc($strategy)?></td>
    <td style="vertical-align:middle" nowrap>
        <a href="<?=route('chartjs.scatter').'?id='.$test->getId()?>"><?=hsc($report)?></a></td>
    <td style="vertical-align:middle">
        <a href="<?=route('chartjs.line').'?id='.$test->getId()?>"><?=$symbol.', '.$period?></a></td>
    <td style="vertical-align:middle"><?=$timeRange?></td>
    <td style="vertical-align:middle"><?=numf($numTrades, 0)?></td>
    <td style="vertical-align:middle"><?=sprintf('%+.1f', $avgPips)?></td>
    <td style="vertical-align:middle"><?=rtrim(sprintf('%.4f', $sharpe), '.0')?></td>
    <td style="vertical-align:middle"><?=rtrim(sprintf('%.4f', $sortino), '.0')?></td>
    <td style="vertical-align:middle"><?=rtrim(sprintf('%.4f', $calmar), '.0')?></td>
    <td style="vertical-align:middle"><?=sprintf('%.0f d', $maxRecoveryTime)?></td>
</tr>
<?}?>

</tbody>
</table>

<script>
$(document).ready(function() {
    $('#testTable').tablesorter({
        theme: getTableSorterTheme('tablesorter-theme') || 'default',
      //debug: true,
    });
});
</script>
