<?php
declare(strict_types=1);

use rosasurfer\ministruts\struts\Tile;

use function rosasurfer\ministruts\asset;

/** @var Tile $navigation */
/** @var Tile $content    */
?>
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <title>Rosatrader</title>
   <meta name="description" content="rosatrader">

   <link rel="stylesheet" href="<?=asset('/css/bootstrap/3.3/css/bootstrap.css')?>">
   <link rel="stylesheet" href="<?=asset('/css/bootstrap/3.3/css/bootstrap-theme.css')?>">
   <link rel="stylesheet" href="<?=asset('/css/bootstrap/assets/css/ie10-viewport-bug-workaround.css')?>">
   <!--[if lt IE 9]>
   <script src="<?=asset('/js/html5shiv-3.7.3.min.js')?>"></script>
   <script src="<?=asset('/js/respond-1.4.2.min.js')?>"></script>
   <![endif]-->
   <script src="<?=asset('/js/jquery/jquery-1.12.4.js')?>"></script>
   <script src="<?=asset('/css/bootstrap/3.3/js/bootstrap.js')?>"></script>
   <script src="<?=asset('/css/bootstrap/assets/js/ie10-viewport-bug-workaround.js')?>"></script>

   <link rel="stylesheet" href="<?=asset('/css/rosatrader.css')?>">

   <script src="<?=asset('/js/moment/moment-2.18.1.js')?>"></script>
   <script src="<?=asset('/js/rosasurfer.js')?>"></script>
   <script src="<?=asset('/js/rosatrader.js')?>"></script>
</head>

<body>
<div id="page">
   <div id="header"><?php $navigation->render()?></div>

   <div id="content"><?php $content->render()?></div>
</div>
</body>
</html>
