<?php
namespace rosasurfer\xtrade\view;
?>
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <title>Xtrade</title>
   <meta name="description" content="Xtrade">

   <link rel="stylesheet" type="text/css" href="<?=asset('/css/bootstrap.min.css')?>"/>
   <link rel="stylesheet" type="text/css" href="<?=asset('/css/xtrade.css')?>"/>

   <script type="text/javascript" src="<?=asset('/js/jquery/jquery-1.12.4.js')?>"></script>
   <script type="text/javascript" src="<?=asset('/js/jquery/jquery-migrate-1.4.1.js')?>"></script>
   <script type="text/javascript" src="<?=asset('/js/bootstrap.min.js')?>"></script>
   <script type="text/javascript" src="<?=asset('/js/chartjs/Chart.bundle-2.6.0.min.js')?>"></script>
   <script type="text/javascript" src="<?=asset('/js/rosasurfer.js')?>"></script>
</head>

<body>
<div id="page">
   <div id="header"><?$navigation->render();?></div>

   <div id="content"><?$content->render();?></div>
</div>
</body>
</html>
